### ISSUE TITLE
days-selected format

### ISSUE THREAD

**Issue by AviFix** [arca-computing/MultipleDatePicker#18]
Hi,

in <multiple-date-picker days-selected="[1404770400000, 1405029600000]"/>
How can i change the date format from timestamp to 'dd-mm-yyyy'?
this is the format i get from my api.

is it possible?

Thank's alot
Avi

**Comment by mgohin** [comment]
Hi,

I don't get your problem, a timestamp is a long number giving milliseconds from 01-01-1970, it's not a formatted date.
Please give me an example of your problem

**Comment by AviFix** [comment]
Hi,

Thanks for your quick reply.

I need the format of the "days-selected" to be ''yyyy-MM-DD" insted of time stamp.

is it possible?

Thank's
Avi

**Comment by mgohin** [comment]
No it's not and will not be, you must convert the ```yyyy-mm-dd``` into a timestamp. 
Because MultipleDatePicker is using [momentjs](http://momentjs.com/) you can use it to convert dates in timestamp like here -> http://momentjs.com/docs/#/parsing/string/
If your date isn't ```yyyy-mm-dd``` you can use -> http://momentjs.com/docs/#/parsing/string-format/

It's quick and easy to do ;)

**Comment by AviFix** [comment]
Thank's alot

**Comment by hrizvi** [comment]
Hi,
How can I change date yyyy-mm-dd to timestamp in day-selected directive array?
I don't want to go on the script side as I am using the calendar through ng-repeat for each id so I want a way to change the date to timestamp from your directive. Otherwise it would a heck of work as I have a deep nested array of date .
