### ISSUE TITLE
WRONG DATE DISPLAYING

### ISSUE THREAD

**Issue by lfsolutions** [arca-computing/MultipleDatePicker#84]
Dear Team,

I am trying to use the library in the project. Whenever I select the date, it is not showing the Correct Date in the Model. 

I have selected 8th, but it is added 7th to it.

Is there anything I have to do?

Here is the screenshot

[
![date](https://cloud.githubusercontent.com/assets/3453238/22863677/cc69945e-f17f-11e6-8013-dd7e6760f16e.png)
](url)

The HTML code is 

` <multiple-date-picker disable-days-after="vm.today" ng-model="vm.selectedDates"/>`

and controller is 

`vm.today = moment();
vm.selectedDates = [];
vm.removeFromSelected = function (dt) {
        vm.selectedDates.splice(vm.selectedDates.indexOf(dt), 1);
}`

**Comment by mgohin** [comment]
Hi,

I'm the team :p

Can you provide a fiddle example ? I would suggest to check if it's a timezone problem.
With a jsfiddle example I can check it on my side :)

**Comment by lfsolutions** [comment]
Its a .net Project and i do not know how to get the FIDDLE for it

**Comment by mgohin** [comment]
The date you have when you select it is UTC (you can see it with the `.000Z`).
I guess it's only when you display it in console, it displays it with your timezone, because you can select/unselect the good dates.
If you want it to be the same as calendar use [moment.utc](http://momentjs.com/docs/#/parsing/utc/) on your ngModel when you send it to your backend.

**Comment by mgohin** [comment]
Any news ?

**Comment by lfsolutions** [comment]
It's working now 

Thanks
